services:
  - type: web
    name: flask-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://avnadmin:AVNS_O3z9kbbw2LFc1tKyV82@pg-35e910ad-istu-00f2.b.aivencloud.com:17636/defaultdb?sslmode=require"

